name: CI

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: scala-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6

      - name: Run scripted tests
        run: sbt ^scripted
