name: CI

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: scala-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SBT_NATIVE_CLIENT: true
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6

      - name: Setup Nexus credentials
        uses: Tapad/gha-nexus-setup-public@master
        with:
          host: nexus.tapad.com
          user: github-actions
          password: ${{ secrets.NEXUS_PASS_FOR_GITHUB_ACTIONS }}

      # - name: Setup Google Cloud SDK
      #   uses: google-github-actions/auth@v0
      #   with:
      #     project_id: tapad-ci
      #     credentials_json: ${{ secrets.CI_DEFAULT_SERVICE_ACCOUNT }}

      - name: Resolve dependencies
        run: sbt update

      - name: Compile all sources
        run: sbt compile

      - name: Run scripted tests
        run: sbt scripted
